scaling_motor_13######################motor######################
python main.py --name motor --num_trajectories 4 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J none  --R none  --G none --grad_H none --output-weight .25 --run_name motor_baseline_4 --experiment scaling_motor_paper --baseline
python main.py --name motor --num_trajectories 4 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R default  --G mlp --output-weight .25 --run_name motor_default_4 --experiment scaling_motor_paper
python main.py --name motor --num_trajectories 4 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R linear  --G linear --grad_H linear --output-weight .25 --run_name motor_prior_4 --experiment scaling_motor_paper --no-normalize-x
python main.py --name motor --num_trajectories 4 --hidden_dim 8 --num_val_trajectories 100 --lr 1e-3 --epochs 1000 --repeat 1 --J default_kan  --R default_kan  --G kan --grad_H gradient_kan  --output-weight .25 --run_name motor_kan_4 --experiment scaling_motor_paper

python main.py --name motor --num_trajectories 8 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J none  --R none  --G none --grad_H none --output-weight .25 --run_name motor_baseline_8 --experiment scaling_motor_paper --baseline
python main.py --name motor --num_trajectories 8 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R default  --G mlp --output-weight .25 --run_name motor_default_8 --experiment scaling_motor_paper
python main.py --name motor --num_trajectories 8 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R linear  --G linear --grad_H linear --output-weight .25 --run_name motor_prior_8 --experiment scaling_motor_paper --no-normalize-x
python main.py --name motor --num_trajectories 8 --hidden_dim 8 --num_val_trajectories 100 --lr 1e-3 --epochs 1000 --repeat 1 --J default_kan  --R default_kan  --G kan --grad_H gradient_kan  --output-weight .25 --run_name motor_kan_8 --experiment scaling_motor_paper

python main.py --name motor --num_trajectories 16 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J none  --R none  --G none --grad_H none --output-weight .25 --run_name motor_baseline_16 --experiment scaling_motor_paper --baseline
python main.py --name motor --num_trajectories 16 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R default  --G mlp --output-weight .25 --run_name motor_default_16 --experiment scaling_motor_paper
python main.py --name motor --num_trajectories 16 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R linear  --G linear --grad_H linear --output-weight .25 --run_name motor_prior_16 --experiment scaling_motor_paper --no-normalize-x
python main.py --name motor --num_trajectories 16 --hidden_dim 8 --num_val_trajectories 100 --lr 1e-3 --epochs 1000 --repeat 1 --J default_kan  --R default_kan  --G kan --grad_H gradient_kan  --output-weight .25 --run_name motor_kan_16 --experiment scaling_motor_paper

python main.py --name motor --num_trajectories 32 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J none  --R none  --G none --grad_H none --output-weight .25 --run_name motor_baseline_32 --experiment scaling_motor_paper --baseline
python main.py --name motor --num_trajectories 32 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R default  --G mlp --output-weight .25 --run_name motor_default_32 --experiment scaling_motor_paper
python main.py --name motor --num_trajectories 32 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R linear  --G linear --grad_H linear --output-weight .25 --run_name motor_prior_32 --experiment scaling_motor_paper --no-normalize-x
python main.py --name motor --num_trajectories 32 --hidden_dim 8 --num_val_trajectories 100 --lr 1e-3 --epochs 1000 --repeat 1 --J default_kan  --R default_kan  --G kan --grad_H gradient_kan  --output-weight .25 --run_name motor_kan_32 --experiment scaling_motor_paper

python main.py --name motor --num_trajectories 64 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J none  --R none  --G none --grad_H none --output-weight .25 --run_name motor_baseline_64 --experiment scaling_motor_paper --baseline
python main.py --name motor --num_trajectories 64 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R default  --G mlp --output-weight .25 --run_name motor_default_64 --experiment scaling_motor_paper
python main.py --name motor --num_trajectories 64 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R linear  --G linear --grad_H linear --output-weight .25 --run_name motor_prior_64 --experiment scaling_motor_paper --no-normalize-x
python main.py --name motor --num_trajectories 64 --hidden_dim 8 --num_val_trajectories 100 --lr 1e-3 --epochs 1000 --repeat 1 --J default_kan  --R default_kan  --G kan --grad_H gradient_kan  --output-weight .25 --run_name motor_kan_64 --experiment scaling_motor_paper
