######################ball######################
python main.py --name ball --num_trajectories 4 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J none  --R none  --G none --grad_H none --output-weight .25 --run_name ball_baseline_4 --experiment scaling_ball_paper --baseline
python main.py --name ball --num_trajectories 4 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R default  --G mlp --output-weight .25 --run_name ball_default_4 --experiment scaling_ball_paper
python main.py --name ball --num_trajectories 4 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J linear  --R default  --G linear --grad_H gradient --output-weight .25 --run_name ball_prior_4 --experiment scaling_ball_paper --no-normalize-x
python main.py --name ball --num_trajectories 4 --hidden_dim 8 --num_val_trajectories 100 --lr 1e-3 --epochs 1000 --repeat 1 --J default_kan  --R default_kan  --G kan --grad_H gradient_kan  --output-weight .25 --run_name ball_kan_4 --experiment scaling_ball_paper

python main.py --name ball --num_trajectories 8 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J none  --R none  --G none --grad_H none --output-weight .25 --run_name ball_baseline_8 --experiment scaling_ball_paper --baseline
python main.py --name ball --num_trajectories 8 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R default  --G mlp --output-weight .25 --run_name ball_default_8 --experiment scaling_ball_paper
python main.py --name ball --num_trajectories 8 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J linear  --R default  --G linear --grad_H gradient --output-weight .25 --run_name ball_prior_8 --experiment scaling_ball_paper --no-normalize-x
python main.py --name ball --num_trajectories 8 --hidden_dim 8 --num_val_trajectories 100 --lr 1e-3 --epochs 1000 --repeat 1 --J default_kan  --R default_kan  --G kan --grad_H gradient_kan  --output-weight .25 --run_name ball_kan_8 --experiment scaling_ball_paper

python main.py --name ball --num_trajectories 16 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J none  --R none  --G none --grad_H none --output-weight .25 --run_name ball_baseline_16 --experiment scaling_ball_paper --baseline
python main.py --name ball --num_trajectories 16 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R default  --G mlp --output-weight .25 --run_name ball_default_16 --experiment scaling_ball_paper
python main.py --name ball --num_trajectories 16 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J linear  --R default  --G linear --grad_H gradient --output-weight .25 --run_name ball_prior_16 --experiment scaling_ball_paper --no-normalize-x
python main.py --name ball --num_trajectories 16 --hidden_dim 8 --num_val_trajectories 100 --lr 1e-3 --epochs 1000 --repeat 1 --J default_kan  --R default_kan  --G kan --grad_H gradient_kan  --output-weight .25 --run_name ball_kan_16 --experiment scaling_ball_paper

python main.py --name ball --num_trajectories 32 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J none  --R none  --G none --grad_H none --output-weight .25 --run_name ball_baseline_31 --experiment scaling_ball_paper --baseline
python main.py --name ball --num_trajectories 32 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R default  --G mlp --output-weight .25 --run_name ball_default_32 --experiment scaling_ball_paper
python main.py --name ball --num_trajectories 32 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J linear  --R default  --G linear --grad_H gradient --output-weight .25 --run_name ball_prior_32 --experiment scaling_ball_paper --no-normalize-x
python main.py --name ball --num_trajectories 32 --hidden_dim 8 --num_val_trajectories 100 --lr 1e-3 --epochs 1000 --repeat 1 --J default_kan  --R default_kan  --G kan --grad_H gradient_kan  --output-weight .25 --run_name ball_kan_32 --experiment scaling_ball_paper

python main.py --name ball --num_trajectories 64 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J none  --R none  --G none --grad_H none --output-weight .25 --run_name ball_baseline_64 --experiment scaling_ball_paper --baseline
python main.py --name ball --num_trajectories 64 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J default  --R default  --G mlp --output-weight .25 --run_name ball_default_64 --experiment scaling_ball_paper
python main.py --name ball --num_trajectories 64 --hidden_dim 32 --num_val_trajectories 100 --lr 1e-3 --epochs 4000 --repeat 1 --J linear  --R default  --G linear --grad_H gradient --output-weight .25 --run_name ball_prior_64 --experiment scaling_ball_paper --no-normalize-x
python main.py --name ball --num_trajectories 64 --hidden_dim 8 --num_val_trajectories 100 --lr 1e-3 --epochs 1000 --repeat 1 --J default_kan  --R default_kan  --G kan --grad_H gradient_kan  --output-weight .25 --run_name ball_kan_64 --experiment scaling_ball_paper
